version: "3"
services:
    app:
        container_name: del-api
        image: del/del-api
        restart: always
        environment: 
            - NODE_ENV=development
        command: bash -c "npm run docker_start_dev"
        ports:
            - "3050:3050"
        links:
            - mongo_del
    mongo_del:
        container_name: mongo_del
        image: mongo
        volumes:
            - ./data:/data/del_api/db
        ports:
            - "27019:27017"