version: "3"
services:
    api:
        container_name: del-api
        image: del/del-api
        restart: always
        volumes:
            - ./.docker_del_apps:/app/applications
        environment: 
            - NODE_ENV=development
        command: bash -c "npm run docker_start_dev"
        ports:
            - "${PORT}:${PORT}"
        links:
            - mongo_del
    mongo_del:
        container_name: mongo_del
        image: mongo:latest
        volumes:
            - ./.docker_del_db:/data/db
        ports:
            - "27019:${DB_PORT}"